import Foundation

var tipo = [caso.redeDeApoio:"Rede de Apoio", caso.alimentacao:"Alimentação", caso.apps:"Apps", caso.direitos:"Direitos", caso.cursoDeGravidas:"Cursos de grávida", caso.ajudaPsicologica:"Ajuda psicológica", caso.depoimento:"Depoimentos"]

enum caso{
    case redeDeApoio
    case alimentacao
    case apps
    case direitos
    case cursoDeGravidas
    case ajudaPsicologica
    case depoimento
    case nenhum
}

struct Tela{
    var titulo:String
    var texto:String
    var imagem:String
    var link:String
    var temLink:Bool
    var tipo:Int
}

struct sugestaoLista{
    static let tela = [
        Tela(titulo: "Pamonha",
             texto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet auctor arcu. Duis dapibus erat vitae varius mattis. Nullam sed rutrum massa. Nam a porta lacus, vel bibendum mi. Pellentesque a nulla a odio cursus consequat vel sit amet magna. Aliquam ornare metus at mi cursus, id dapibus nibh ullamcorper. Praesent et risus id metus rutrum tempus. Proin nec velit metus. Nulla faucibus aliquam mollis.\n\nDonec blandit congue nulla sed ullamcorper. Sed tincidunt tincidunt enim, nec accumsan urna eleifend at. Aenean eleifend ligula eget odio viverra porta. Proin rutrum tortor in leo sagittis mollis. Nullam justo massa, cursus ac malesuada vitae, efficitur vel nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam commodo aliquam massa et iaculis. Vestibulum sagittis urna quam, et vestibulum est molestie at. Fusce porttitor, tellus in bibendum tempor, libero urna rhoncus urna, eget volutpat nulla neque ut justo. Suspendisse dictum congue nisl, sit amet mollis massa ultricies vel. Quisque dictum eros eget convallis gravida. Duis semper sapien eu lacus consequat, a posuere velit gravida.\n\nPellentesque ac dolor mi. Fusce eleifend vulputate turpis, eget aliquet dui fermentum at. Integer venenatis elementum ex vitae lobortis. Donec nec lobortis dui, non suscipit mi. Mauris vitae nulla posuere, laoreet sem eu, aliquam felis. Duis mattis lacinia purus, sed laoreet dui. Praesent laoreet commodo dignissim. Proin venenatis bibendum purus quis tincidunt. Curabitur consectetur ac purus et feugiat. Pellentesque convallis tellus sed pulvinar tristique. Cras dui mauris, egestas sit amet magna nec, rutrum dignissim ex. Morbi tristique sapien eget suscipit viverra. Macarrao",
             imagem: "Image",
             link: "https://www.youtube.com/watch?v=piAiy5vlC9k",
             temLink: true, tipo:0),
        Tela(titulo: "Pamonha 2",
             texto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet auctor arcu. Duis dapibus erat vitae varius mattis. Nullam sed rutrum massa. Nam a porta lacus, vel bibendum mi. Pellentesque a nulla a odio cursus consequat vel sit amet magna. Aliquam ornare metus at mi cursus, id dapibus nibh ullamcorper. Praesent et risus id metus rutrum tempus. Proin nec velit metus. Nulla faucibus aliquam mollis.\n\nDonec blandit congue nulla sed ullamcorper. Sed tincidunt tincidunt enim, nec accumsan urna eleifend at. Aenean eleifend ligula eget odio viverra porta. Proin rutrum tortor in leo sagittis mollis. Nullam justo massa, cursus ac malesuada vitae, efficitur vel nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam commodo aliquam massa et iaculis. Vestibulum sagittis urna quam, et vestibulum est molestie at. Fusce porttitor, tellus in bibendum tempor, libero urna rhoncus urna, eget volutpat nulla neque ut justo. Suspendisse dictum congue nisl, sit amet mollis massa ultricies vel. Quisque dictum eros eget convallis gravida. Duis semper sapien eu lacus consequat, a posuere velit gravida.\n\nPellentesque ac dolor mi. Fusce eleifend vulputate turpis, eget aliquet dui fermentum at. Integer venenatis elementum ex vitae lobortis. Donec nec lobortis dui, non suscipit mi. Mauris vitae nulla posuere, laoreet sem eu, aliquam felis. Duis mattis lacinia purus, sed laoreet dui. Praesent laoreet commodo dignissim. Proin venenatis bibendum purus quis tincidunt. Curabitur consectetur ac purus et feugiat. Pellentesque convallis tellus sed pulvinar tristique. Cras dui mauris, egestas sit amet magna nec, rutrum dignissim ex. Morbi tristique sapien eget suscipit viverra. pamonha",
             imagem: "Image 1",
             link: "https://idmsa.apple.com/signin?language=GB-EN&rv=1&path=/account/&appIdKey=891bd3417a7776362562d2197f89480a8547b108fd934911bcbea0110d07f757",
             temLink: false, tipo:2),
        Tela(titulo: "Margarina",
             texto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet auctor arcu. Duis dapibus erat vitae varius mattis. Nullam sed rutrum massa. Nam a porta lacus, vel bibendum mi. Pellentesque a nulla a odio cursus consequat vel sit amet magna. Aliquam ornare metus at mi cursus, id dapibus nibh ullamcorper. Praesent et risus id metus rutrum tempus. Proin nec velit metus. Nulla faucibus aliquam mollis.\n\nDonec blandit congue nulla sed ullamcorper. Sed tincidunt tincidunt enim, nec accumsan urna eleifend at. Aenean eleifend ligula eget odio viverra porta. Proin rutrum tortor in leo sagittis mollis. Nullam justo massa, cursus ac malesuada vitae, efficitur vel nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam commodo aliquam massa et iaculis. Vestibulum sagittis urna quam, et vestibulum est molestie at. Fusce porttitor, tellus in bibendum tempor, libero urna rhoncus urna, eget volutpat nulla neque ut justo. Suspendisse dictum congue nisl, sit amet mollis massa ultricies vel. Quisque dictum eros eget convallis gravida. Duis semper sapien eu lacus consequat, a posuere velit gravida.\n\nPellentesque ac dolor mi. Fusce eleifend vulputate turpis, eget aliquet dui fermentum at. Integer venenatis elementum ex vitae lobortis. Donec nec lobortis dui, non suscipit mi. Mauris vitae nulla posuere, laoreet sem eu, aliquam felis. Duis mattis lacinia purus, sed laoreet dui. Praesent laoreet commodo dignissim. Proin venenatis bibendum purus quis tincidunt. Curabitur consectetur ac purus et feugiat. Pellentesque convallis tellus sed pulvinar tristique. Cras dui mauris, egestas sit amet magna nec, rutrum dignissim ex. Morbi tristique sapien eget suscipit viverra. Cenoura",
             imagem: "Image 2",
             link: "https://www.hackingwithswift.com/quick-start/swiftui/how-to-open-web-links-in-safari",
             temLink: true, tipo:1),
        Tela(titulo: "Bebe",
             texto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet auctor arcu. Duis dapibus erat vitae varius mattis. Nullam sed rutrum massa. Nam a porta lacus, vel bibendum mi. Pellentesque a nulla a odio cursus consequat vel sit amet magna. Aliquam ornare metus at mi cursus, id dapibus nibh ullamcorper. Praesent et risus id metus rutrum tempus. Proin nec velit metus. Nulla faucibus aliquam mollis.\n\nDonec blandit congue nulla sed ullamcorper. Sed tincidunt tincidunt enim, nec accumsan urna eleifend at. Aenean eleifend ligula eget odio viverra porta. Proin rutrum tortor in leo sagittis mollis. Nullam justo massa, cursus ac malesuada vitae, efficitur vel nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam commodo aliquam massa et iaculis. Vestibulum sagittis urna quam, et vestibulum est molestie at. Fusce porttitor, tellus in bibendum tempor, libero urna rhoncus urna, eget volutpat nulla neque ut justo. Suspendisse dictum congue nisl, sit amet mollis massa ultricies vel. Quisque dictum eros eget convallis gravida. Duis semper sapien eu lacus consequat, a posuere velit gravida.\n\nPellentesque ac dolor mi. Fusce eleifend vulputate turpis, eget aliquet dui fermentum at. Integer venenatis elementum ex vitae lobortis. Donec nec lobortis dui, non suscipit mi. Mauris vitae nulla posuere, laoreet sem eu, aliquam felis. Duis mattis lacinia purus, sed laoreet dui. Praesent laoreet commodo dignissim. Proin venenatis bibendum purus quis tincidunt. Curabitur consectetur ac purus et feugiat. Pellentesque convallis tellus sed pulvinar tristique. Cras dui mauris, egestas sit amet magna nec, rutrum dignissim ex. Morbi tristique sapien eget suscipit viverra. Chiclete",
             imagem: "Image 3",
             link: "https://chat.openai.com",
             temLink: false, tipo:3),
             
        Tela(titulo: "Pasta",
             texto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet auctor arcu. Duis dapibus erat vitae varius mattis. Nullam sed rutrum massa. Nam a porta lacus, vel bibendum mi. Pellentesque a nulla a odio cursus consequat vel sit amet magna. Aliquam ornare metus at mi cursus, id dapibus nibh ullamcorper. Praesent et risus id metus rutrum tempus. Proin nec velit metus. Nulla faucibus aliquam mollis.\n\nDonec blandit congue nulla sed ullamcorper. Sed tincidunt tincidunt enim, nec accumsan urna eleifend at. Aenean eleifend ligula eget odio viverra porta. Proin rutrum tortor in leo sagittis mollis. Nullam justo massa, cursus ac malesuada vitae, efficitur vel nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam commodo aliquam massa et iaculis. Vestibulum sagittis macarrao urna quam, et vestibulum est molestie at. Fusce porttitor, tellus in bibendum tempor, libero urna rhoncus urna, eget volutpat nulla neque ut justo. Suspendisse dictum congue nisl, sit amet mollis massa ultricies vel. Quisque dictum eros eget convallis gravida. Duis semper sapien eu lacus consequat, a posuere velit gravida.\n\nPellentesque ac dolor mi. Fusce eleifend vulputate turpis, eget aliquet dui fermentum at. Integer venenatis elementum ex vitae lobortis. Donec nec lobortis dui, non suscipit mi. Mauris vitae nulla posuere, laoreet sem eu, aliquam felis. Duis mattis lacinia purus, sed laoreet dui. Praesent laoreet commodo dignissim. Proin venenatis bibendum purus quis tincidunt. Curabitur consectetur ac purus et feugiat. Pellentesque convallis tellus sed pulvinar tristique. Cras dui mauris, egestas sit amet magna nec, rutrum dignissim ex. Morbi tristique sapien eget suscipit viverra.",
             imagem: "Image 4",
             link: "https://chat.openai.com",
             temLink: false, tipo:4),
             
        Tela(titulo: "Lagosta",
             texto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet auctor arcu. Duis dapibus erat vitae varius mattis. Nullam sed rutrum massa. Nam a porta lacus, vel bibendum mi. Pellentesque a nulla a odio cursus consequat vel sit amet magna. Aliquam ornare metus at mi cursus, id dapibus nibh ullamcorper. Praesent et risus id metus rutrum tempus. Proin nec velit metus. Nulla faucibus aliquam mollis.\n\nDonec macarrone blandit congue nulla sed ullamcorper. Sed tincidunt tincidunt enim, nec accumsan urna eleifend at. Aenean eleifend ligula eget odio viverra porta. Proin rutrum tortor in leo sagittis mollis. Nullam justo massa, cursus ac malesuada vitae, efficitur vel nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam commodo aliquam massa et iaculis. Vestibulum sagittis urna quam, et vestibulum est molestie at. Fusce porttitor, tellus in bibendum tempor, libero urna rhoncus urna, eget volutpat nulla neque ut justo. Suspendisse dictum congue nisl, sit amet mollis massa ultricies vel. Quisque dictum eros eget convallis gravida. Duis semper sapien eu lacus consequat, a posuere velit gravida.\n\nPellentesque ac dolor mi. Fusce eleifend vulputate turpis, eget aliquet dui fermentum at. Integer venenatis elementum ex vitae lobortis. Donec nec lobortis dui, non suscipit mi. Mauris vitae nulla posuere, laoreet sem eu, aliquam felis. Duis mattis lacinia purus, sed laoreet dui. Praesent laoreet commodo dignissim. Proin venenatis bibendum purus quis tincidunt. Curabitur consectetur ac purus et feugiat. Pellentesque convallis tellus sed pulvinar tristique. Cras dui mauris, egestas sit amet magna nec, rutrum dignissim ex. Morbi tristique sapien eget suscipit viverra.",
             imagem: "Image 5",
             link: "https://chat.openai.com",
             temLink: true, tipo:1),
             
        Tela(titulo: "Crédito",
             texto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet auctor arcu. Duis dapibus erat vitae varius mattis. Nullam sed rutrum massa. Nam a porta lacus, vel bibendum mi. Pellentesque a nulla a odio cursus consequat vel sit amet magna. Aliquam ornare metus at mi cursus, id dapibus nibh ullamcorper. Praesent et risus id metus rutrum tempus. Proin nec velit metus. Nulla faucibus aliquam mollis.\n\nDonec blandit congue nulla sed ullamcorper. Sed tincidunt tincidunt enim, nec accumsan urna eleifend at. Aenean eleifend ligula eget odio viverra porta. Proin rutrum tortor in leo sagittis mollis. Nullam justo massa, cursus ac malesuada vitae, efficitur vel nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam commodo aliquam massa et iaculis. Vestibulum sagittis urna quam, et vestibulum est molestie at. Fusce porttitor, tellus in bibendum tempor, libero urna rhoncus urna, eget volutpat nulla neque ut justo. Suspendisse dictum congue nisl, sit amet mollis massa ultricies vel. Quisque dictum eros eget convallis gravida. Duis semper sapien eu lacus consequat, a posuere velit gravida.\n\nPellentesque ac dolor mi. Fusce eleifend vulputate turpis, eget aliquet dui fermentum at. Integer venenatis elementum ex vitae lobortis. Donec nec lobortis dui, non suscipit mi. Mauris vitae nulla posuere, laoreet sem eu, aliquam felis. Duis mattis lacinia purus, sed laoreet dui. Praesent laoreet commodo dignissim. Proin venenatis bibendum purus quis tincidunt. Curabitur consectetur ac purus et feugiat. Pellentesque convallis tellus sed pulvinar tristique. Cras dui mauris, egestas sit amet magna nec, rutrum dignissim ex. Morbi tristique sapien eget suscipit viverra. chicleta",
             imagem: "Image 6",
             link: "https://chat.openai.com",
             temLink: true, tipo:1)
    ]
}
